apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sampleapp-deployment
  namespace: devops3
  labels:
    app: sampleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: mittalyash32/myapp
        ports:
        - containerPort: 9080
      imagePullSecrets:
        - name: springapplkey
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  namespace: devops3
  labels:
    app: sampleapp
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30003
  selector:
    app: sampleapp
