apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: jenkins
    namespace: devops3
spec:
  replicas: 1
  selector:
    matchLabels:
       app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: mittalyash32/myjenkinsimage
          ports:
            - name: http-port
              containerPort: 8080
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-home
          hostPath:
              path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops3
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
  selector:
    app: jenkins
